### ISSUE TITLE
example integrate crashed.

### ISSUE THREAD

**Issue by songww** [Smithay/smithay-egui#9]
os: Debian Testing
wm: cosmic-comp
teminal: kitty
command: `cargo run --example integrate`
last log:
> Jan 06 15:57:16.143 DEBG [GL] Buffer detailed info: Buffer object 4 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations., smithay_module: renderer_gles2, smithay_module: backend_winit
> Jan 06 15:57:16.144 DEBG [GL] Buffer detailed info: Buffer object 2 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STREAM_DRAW) will use VIDEO memory as the source for buffer object operations., smithay_module: renderer_gles2, smithay_module: backend_winit
> Jan 06 15:57:16.148 ERRO [EGL] 0x300d (BAD_SURFACE) eglStreamFlushNV: EGL_BAD_SURFACE error: In eglSwapBuffers: Invalid EGLSurface (0x5589411d4151)
> , backend: egl
> Jan 06 15:57:16.149 ERRO [EGL] 0x3003 (BAD_ALLOC) eglCreatePlatformWindowSurfaceEXT: EGL_BAD_ALLOC error: In internal function: Additional INFO may be available
> , backend: egl
> Error: The context has been lost, it needs to be recreated: EGL failed to allocate resources for the requested operation.

**Comment by Drakulix** [comment]
> ERRO [EGL] 0x300d (BAD_SURFACE) eglStreamFlushNV: EGL_BAD_SURFACE error: In eglSwapBuffers: Invalid EGLSurface (0x5589411d4151)

Interesting, you seems to be running on a nvidia-gpu (as apparent from the internal use of `eglStreamFlushNV`). Which driver version are you on? Also which version is the `egl-wayland` library on your system? (I am not sure if that is packaged separately from the nvidia-driver, but older versions of this library had various issues with winit.)

This is definitely the winit-backend in smithay failing (which shouldn't be an error of smithay-egui specifically).
Can you run `anvil` from the `smithay`-repo? Can you run other winit apps without this issue?

You could also try running the example via X11 (which just to note is not supported on cosmic-comp) via setting `WINIT_UNIX_BACKEND=x11` before running it. Does that work?

Tbh, if you were not using Debian Testing, I would kinda expect this to be an issue of outdated libraries, as the whole wayland stack from nvidia is still quite new and early versions were littered with subtle bugs, that have since then been ironed out.

**Comment by songww** [comment]
It works in Gnome Wayland with `WINIT_UNIX_BACKEND=x11`.

thanks.
